apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://alexeigarban.com
      title: My Dashboard
      icon: dashboard
spec:
  type: library
  owner: user:guest
  lifecycle: experimental